import axios from "axios";
import yts from "yt-search";
import config from '../config.cjs';

const play = async (m, gss) => {
  const prefix = config.PREFIX;
  const cmd = m.body.startsWith(prefix) ? m.body.slice(prefix.length).split(" ")[0].toLowerCase() : "";
  const args = m.body.slice(prefix.length + cmd.length).trim().split(" ");

  if (cmd === "play") {
    if (args.length === 0 || !args.join(" ")) {
      return m.reply("*Please provide a song name or keywords to search for.*");
    }

    const searchQuery = args.join(" ");
    m.reply("*🎧 Searching for the song...*");

    try {
      const searchResults = await yts(searchQuery);
      if (!searchResults.videos || searchResults.videos.length === 0) {
        return m.reply(`❌ No results found for "${searchQuery}".`);
      }

      const firstResult = searchResults.videos[0];
      const videoUrl = firstResult.url;
      
      // Format the views with commas
      const formattedViews = parseInt(firstResult.views.replace(/,/g, '')).toLocaleString();
      
      // Calculate time since publication
      const publishedDate = new Date(firstResult.ago);
      const currentDate = new Date();
      const yearsAgo = currentDate.getFullYear() - publishedDate.getFullYear();

      // Create a rich media message with image
      const message = {
        image: { url: firstResult.thumbnail },
        caption: `🎵 *${firstResult.title}* 🎵\n\n` +
                 `👤 *Artist:* ${firstResult.author.name}\n` +
                 `⏱️ *Duration:* ${firstResult.timestamp}\n` +
                 `👀 *Views:* ${formattedViews}\n` +
                 `📅 *Published:* ${yearsAgo} years ago\n` +
                 `🔗 *URL:* ${firstResult.url}\n\n` +
                 `_Powered By Mr Caseyrhodes_\n` +
                 `> *GENERATED BY CASEYRHODES*\n\n` +
                 `Select download format:`,
        footer: "SONG DOWNLOADER",
        buttons: [
          { buttonId: `${prefix}playmp3 ${firstResult.videoId}`, buttonText: { displayText: '🎵 Audio (Play)' }, type: 1 },
          { buttonId: `${prefix}playdoc ${firstResult.videoId}`, buttonText: { displayText: '📄 Document (Save)' }, type: 1 },
          { buttonId: `${prefix}playmp4 ${firstResult.videoId}`, buttonText: { displayText: '🎥 Video' }, type: 1 }
        ],
        headerType: 4
      };

      // Send the message with image and buttons
      await gss.sendMessage(m.from, message, { quoted: m });

    } catch (error) {
      console.error(error);
      m.reply("❌ An error occurred while processing your request.");
    }
  }

  // Handle the button selections
  if (cmd === "playmp3" || cmd === "playmp4" || cmd === "playdoc") {
    if (args.length === 0) {
      return m.reply("*Please provide a video ID.*");
    }

    const videoId = args[0];
    const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
    
    m.reply("*⬇️ Downloading your media...*");

    try {
      let apiUrl, mimetype, fileName, messageOptions;
      
      if (cmd === "playmp3") {
        // MP3 Audio
        apiUrl = `https://api.davidcyriltech.my.id/download/ytmp3?url=${videoUrl}`;
        const response = await axios.get(apiUrl);
        
        if (!response.data.success) {
          return m.reply(`❌ Failed to fetch audio.`);
        }

        const { title, download_url } = response.data.result;
        fileName = title.replace(/[^\w\s]/gi, '') + '.mp3';
        
        // Get video info for thumbnail
        const searchResults = await yts({ videoId });
        const videoInfo = searchResults.videos[0];
        
        // Send as audio message with thumbnail
        await gss.sendMessage(
          m.from,
          {
            audio: { url: download_url },
            mimetype: "audio/mp4",
            ptt: false,
            contextInfo: {
              externalAdReply: {
                title: title,
                body: "Audio Download",
                thumbnail: videoInfo.thumbnail,
                mediaType: 2,
                mediaUrl: videoUrl,
                sourceUrl: videoUrl
              }
            }
          },
          { quoted: m }
        );
        
      } else if (cmd === "playmp4") {
        // MP4 Video
        apiUrl = `https://api.davidcyriltech.my.id/download/ytmp4?url=${videoUrl}`;
        const response = await axios.get(apiUrl);
        
        if (!response.data.success) {
          return m.reply(`❌ Failed to fetch video.`);
        }

        const { title, download_url } = response.data.result;
        
        // Get video info for thumbnail
        const searchResults = await yts({ videoId });
        const videoInfo = searchResults.videos[0];
        
        // Send as video message
        await gss.sendMessage(
          m.from,
          {
            video: { url: download_url },
            caption: title,
            mimetype: "video/mp4",
            contextInfo: {
              externalAdReply: {
                title: title,
                body: "Video Download",
                thumbnail: videoInfo.thumbnail,
                mediaType: 2,
                mediaUrl: videoUrl,
                sourceUrl: videoUrl
              }
            }
          },
          { quoted: m }
        );
        
      } else if (cmd === "playdoc") {
        // Document format
        apiUrl = `https://api.davidcyriltech.my.id/download/ytmp3?url=${videoUrl}`;
        const response = await axios.get(apiUrl);
        
        if (!response.data.success) {
          return m.reply(`❌ Failed to fetch audio.`);
        }

        const { title, download_url } = response.data.result;
        fileName = title.replace(/[^\w\s]/gi, '') + '.mp3';
        
        // Get video info for thumbnail
        const searchResults = await yts({ videoId });
        const videoInfo = searchResults.videos[0];
        
        // Send as document with thumbnail
        await gss.sendMessage(
          m.from,
          {
            document: { url: download_url },
            mimetype: "audio/mpeg",
            fileName: fileName,
            contextInfo: {
              externalAdReply: {
                title: title,
                body: "Document Download",
                thumbnail: videoInfo.thumbnail,
                mediaType: 2,
                mediaUrl: videoUrl,
                sourceUrl: videoUrl
              }
            }
          },
          { quoted: m }
        );
      }
      
    } catch (error) {
      console.error(error);
      m.reply("❌ An error occurred while downloading your media.");
    }
  }
};

export default play;
